### ISSUE TITLE
`lla init` fails with "Plugin directory does not exist"

### ISSUE THREAD

**Issue by Chaz6** [triyanox/lla#7] opened 2024-11-24 19:57 UTC
```bash
cargo install lla
lla init

# Error: Plugin("Plugin directory does not exist: \"/home/chaz/.config/lla/plugins\"")
```

**Comment by triyanox** [comment] 2024-11-24 22:18
Thank you @Chaz6 for opening this issue! The issue is fixed on v0.2.6 you will be able to use the `init` command without any problems by running `cargo install lla` to get the new update

**Closed** 2024-11-24 22:41 UTC
